package automod_legacy

// These words are listed in in alphabethical order.
var BuiltinSwearWords = map[string]bool{
	"anal":        true,
	"anus":        true,
	"arse":        true,
	"ass":         true,
	"b1tch":       true,
	"ballsack":    true,
	"bastard":     true,
	"bitch":       true,
	"biatch":      true,
	"blowjob":     true,
	"bollock":     true,
	"bollok":      true,
	"boner":       true,
	"boob":        true,
	"boobs":       true,
	"buttplug":    true,
	"clitoris":    true,
	"cock":        true,
	"cum":         true,
	"cunt":        true,
	"dick":        true,
	"dildo":       true,
	"dyke":        true,
	"erection":    true,
	"fag":         true,
	"faggot":      true,
	"feck":        true,
	"fellate":     true,
	"fellatio":    true,
	"felching":    true,
	"fuck":        true,
	"fucks":       true,
	"fudgepacker": true,
	"genitals":    true,
	"jerk":        true,
	"jizz":        true,
	"knobend":     true,
	"labia":       true,
	"masturbate":  true,
	"muff":        true,
	"nigger":      true,
	"nigga":       true,
	"penis":       true,
	"piss":        true,
	"poop":        true,
	"pube":        true,
	"pussy":       true,
	"scrotum":     true,
	"sex":         true,
	"shit":        true,
	"sh1t":        true,
	"slut":        true,
	"smegma":      true,
	"spunk":       true,
	"tit":         true,
	"tranny":      true,
	"trannies":    true,
	"tosser":      true,
	"turd":        true,
	"twat":        true,
	"vagina":      true,
	"wank":        true,
	"whore":       true,
	"tits":        true,
	"titty":       true,
	"asshole":     true,
	"fvck":        true,
	"asshat":      true,
	"pu55y":       true,
	"pen1s":       true,
	"perdol"       true,
	"odpierdol"    true,
	"nigg0"        true,
	"nigg"         true,
	"zabije cie"   true,
    "odetne ci głowe"        true,
	"odjebie ci głowe"       true,
	"odpierdole ci głowe"    true,
	"kutas"       true,
	"kurwa"       true,
	"bo ci coś zrobie zara"  true,
	"cyc"         true,
	"cycek"       true,
	"cycki"       true,
	"cipa"        true,
	"sperma"      true,
	"zrób lud"    true,
	"zrób mi loda"          true,
	"idz sie piepszyć"      true,
	"idz sie piepszyc"      true,
	idz się piepszyć"       true,
	
}
